options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude: ['breakpoint', 'bp', 'link-pseudo-classes']

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 2
  no-debug: 2
  # Enable when ignore in a file is available
  no-duplicate-properties: 0
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  # Enable when ignore in a file is available
  no-misspelled-properties: 0
  no-qualifying-elements: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  # Enable when ignore in a file is available
  no-vendor-prefixes: 0
  no-warn: 2
  property-units: 0

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2

  # Name Formats
  class-name-format:
    - 2
    - convention: hyphenatedbem
  placeholder-name-format:
    - 2
    - convention: hyphenatedbem
  function-name-format: 2
  id-name-format: 0
  mixin-name-format: 2
  variable-name-format: 2

  # Style Guide
  bem-depth: 0
  border-zero: 2
  brace-style: 2
  clean-import-paths: 0
  empty-args: 2
  hex-length:
    - 2
    - style: long
  hex-notation: 2
  indentation: 2
  leading-zero: 2
  nesting-depth:
    - 2
    - max-depth: 3
  property-sort-order:
    - 2
    - order: recess
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
